### PR TITLE
Bytestring 0.11

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
I think now @bgamari should be able to setup the CI here.

**Comment by bgamari** [comment]
CI has been enabled. @phadej, could you rebase?

**Comment by phadej** [comment]
Rebased

**Comment by phadej** [comment]
CI green

**Comment by bgamari** [comment]
Thanks!

**Comment by phadej** [comment]
Can a release with this patch be made, ping @bgamari.

(I get numerous requests to support `bytestring-0.11` and most of them are blocked on `attoparsec`).

**Pull request merged**
