### PR TITLE
Update metadata bgamari -> haskell

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
ping @bgamari

**Comment by phadej** [comment]
ping

**Comment by phadej** [comment]
ping @bgamari

**Comment by andreasabel** [comment]
@bgamari Can this PR be merged or are there issues?  (Note this has already been duplicated in #184.)

[Seeing a PR unhandled for so long might be discouraging PRs in general...]

**Comment by phadej** [comment]
Friendly yearly ping. (Maybe also worth removing Bryan from maintainers, as he isn't one. C.f. #208. Ping @bgamari).

**Pull request closed without merging**
